---
title: "This is the big title"
author: "Qinyu Xiao"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    df_print: paged
    code_folding: show
    theme: flatly
    toc: true
    toc_float: true
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo        = TRUE,
  dpi         = 300,
  fig.width   = 7,
  collapse    = FALSE,
  cache       = FALSE,
  comment     = "",
  strip.white = TRUE,
  warning     = FALSE, # Remove warnings to improve readability
  message     = FALSE,
  fig.align   = "center"
)
options(width = 140)
```

# Preparation

```{r load-packages, results='hide'}
# Indicate required packages
pkgs <- c(
  # Data wrangling packages
  "readxl",              # read Excel file
  "writexl",             # write Excel file
  "excluder",            # for exclusion on survey data
  "tidyverse",           # for data wrangling
  # tidyverse includes ggplot2, purrr, tibble, dplyr, tidyr, stringr, readr, and forcats
  
  # Analysis packages
  "ggstatsplot",         # for easy data analysis and visualization
  "psych",               # for common psychological analyses
  "lme4",                # linear mixed effects modeling
  "lmerTest",            # Tests for linear mixed effects models
  "lavaan",              # factor analysis and SEM
  "afex",                # ANOVA
  "rstatix",             # pipe-friendly framework of basic statistical tests
  "correlation",         # correlational analysis
  "effectsize",          # calculation of effect sizes
  "pwr",                 # power analysis for simple designs
  
  # Meta-analysis
  "metafor",             # meta-analysis
  "metaviz",             # visualization of meta-analysis results
  "puniform",            # p-uniform analysis
  
  # Visualization packages
  "ggplot2",             # data visualization
  "patchwork"            # for combining plots into one
  
  # Add more packages
)

# Find out which packages have not been installed
new_pkgs <- pkgs[!(pkgs %in% installed.packages()[, "Package"])]

# Install new packages
if (length(new_pkgs)) install.packages(new_pkgs, dependencies = TRUE)

# Load the packages
lapply(pkgs, library, character.only = TRUE)
```

```{r load-data, message=FALSE, warning=FALSE}

```

Make sure that data are of proper types.

```{r}
# Numeric columns
dat <- dat %>% mutate(
  across(
    c(which(colnames(dat) == "subject"):which(colnames(dat) == "english")),
    as.numeric
  )
)
```



# Descriptives {.tabset}

## Gender

```{r}
# Gender distribution
# Change the variable name to match the name in the data set
# Make sure that it is a factor variable
# This also applies to other categorical variables
table(dat$gender) %>% as.data.frame() %>%
  rename(Gender = Var1) %>%
  # In percentages
  mutate(`%` = round(100 * Freq / nrow(dat), digits = 1))
```

## Age

```{r}
# Age descriptives
# This also applies to other continuous variables
dat %>% filter(!is.na(age)) %>%
  # Use group_by() when looking for results for separate groups
  # group_by(gender) %>%
  summarise(mean = round(mean(age), 2),
            sd = round(sd(age), 2),
            median = median(age),
            lowest = range(age)[1],
            highest = range(age)[2]) %>%
  as.data.frame()


# UPDATE!!!
# Number of participants who did not disclose age
nrow(dat[dat$age == 99, ])

# Age distribution
dat %>% filter(age != 99) %>%
  summarise(
    mean = round(mean(age), 2),
    sd = round(sd(age), 2),
    median = median(age),
    lowest = range(age)[1],
    highest = range(age)[2]
  ) %>%
  as.data.frame()


```

# Visualization

```{r, comment='', message=FALSE, warning=FALSE, fig.height=5, fig.width=8, dpi=300}
# Un-comment these when generating figure files
# tiff("figure_name.tiff",
#      units = "in",
#      width = 4,
#      height = 5,
#      res = 300,
#      compression = "lzw")



# Un-comment the below line of code when generating figure files
# dev.off()
```

# Statistical analysis

# Session information

To make sure that the analyses above are reproducible, it is necessary that we indicate the versions of the packages that we used.

```{r session-info, comment=''}
pander(sessionInfo(), compact = FALSE)
```

The `report` package would [come in handy](https://twitter.com/Dom_Makowski/status/1368394759392227334?s=20). But it is still not on CRAN yet.

```{r}
# report::report_packages(include_R = FALSE) %>%
#   summary() %>%
#   data.frame() %>%
#   rownames_to_column("package") %>%
#   select(package) %>%
#   arrange(package)
```






