---
title: "One-sample t-tests"
author: "Qinyu Xiao"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    df_print: paged
    code_folding: hide
    theme: flatly
    toc: true
    toc_float: true
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.width = 7,
  collapse = FALSE,
  cache = FALSE,
  comment = "",
  strip.white = TRUE,
  warning = FALSE, # Exclude warnings to improve readability
  messages = FALSE,
  fig.align = "center"
)
options(width = 140)
```

# Preparation

```{r load-packages, results='hide'}
# Indicate required packages
pkgs <- c(
  "tidyverse",
  "statsExpressions"
)

# Find out which pacakges have not been installed
new_pkgs <- pkgs[!(pkgs %in% installed.packages()[, "Package"])]

# Install new packages
if (length(new_pkgs)) install.packages(new_pkgs, dependencies = TRUE)

# Load the packages
lapply(pkgs, library, character.only = TRUE)
```

# Student's t-test



# Multiple tests at once

```{r multiple-tests}
set.seed(123)

# Running one-sample tests for all levels of `cyl`
mtcars %>%
  group_by(cyl) %>%
  group_modify(~ one_sample_test(.x, wt, test.value = 3), .keep = TRUE) %>%
  ungroup()
```












